-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 03, 2025 at 08:56 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `wp2_news_portal`
--

-- --------------------------------------------------------

--
-- Table structure for table `news`
--

CREATE TABLE `news` (
  `id` int(11) NOT NULL,
  `naslov` varchar(255) NOT NULL,
  `sadrzaj` text NOT NULL,
  `datum` datetime NOT NULL DEFAULT current_timestamp(),
  `kategorija` varchar(50) NOT NULL,
  `slika_url` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `news`
--

INSERT INTO `news` (`id`, `naslov`, `sadrzaj`, `datum`, `kategorija`, `slika_url`) VALUES
(7, 'Jutros u BiH pretežno oblačno: Biometeorološke prilike relativno nepovoljne', 'Jutros je u Bosni i Hercegovini pretežno oblačno vrijeme. U Bosni po kotlinama ima magle. Kiša je zabilježena u Hercegovini, centralnim i istočnim područjima Bosne.\n\nTokom dana u Bosni i Hercegovini preovladavat će umjereno do pretežno oblačno vrijeme. Prije podne po kotlinama Bosne može biti magle. U prvom dijelu dana kiša u Hercegovini, ponegdje u centralnim, istočnim i zapadnim područjima Bosne.\n\nNa planinama slab snijeg. U ostatku dana ili tokom noći slaba kiša ponegdje na jugu i istoku zemlje. Vjetar slab, u većem dijelu zemlje, južni i jugozapadni. Dnevna temperatura zraka kretat će se od 4 do 10, na jugu zemlje do 14 stepeni.\n\nBiometeorološka prognoza relativno je nepovoljna. Pod uticajem pogoršanja, povremene kiše i južnog strujanja, tegobe kod hroničnih bolesnika i meteoropata djelimično će se pojačati, izraženije u poslijepodnevnim i noćnim satima.', '2025-12-03 08:37:05', 'Vremenska Prognoza', 'https://tuzlanski.ba/wp-content/uploads/2023/05/oblacno-vrijeme.jpg?v1764745227'),
(8, 'Mokar kolovoz, odroni i magla usporavaju saobraćaj širom BiH: Vozačima se savjetuje dodatni oprez', 'Pretežno mokar kolovoz i povećana opasnost od odrona karakterišu ovoga jutra saobraćajnu situaciju u većem dijelu Bosne i Hercegovine. Dodatne probleme pričinjava i smanjena vidljivost zbog magle, koja na pojedinim dionicama smanjuje vidljivost na manje od 50 metara.\n\n\"Vozite oprezno i prilagodite vožnju i brzinu trenutnom stanju na cestama\", saopćeno je iz BIHAMK-a.\n\nZbog radova na zamjeni rasvjetnih tijela za saobraćaj je zatvorena cijev u tunelu Igman, na dionici autoceste A-1 Sarajevo zapad-Lepenica. Saobraća se dvosmjerno suprotnom stranom autoceste.\n\nZbog izvođenja radova na implementaciji kablovske kanalizacije na dionici autoceste A1 Kakanj-Visoko, za saobraćaj je zatvorena vozna i zaustavna traka.\n\nU toku je sanacija klizišta u mjestu Sijeračke stijene na magistralnoj cesti Dobro Polje-Miljevina, gdje u vremenu od 08 do 17 sati dolazi do obustava u trajanju do 45 minuta.\n\nRadovi su aktuelni i na dionici autoceste A-1 Podlugovi-Sarajevo sjever, kao i na magistralnim cestama: Semizovac-Olovo, Jajce-Crna Rijeka, Bileća-Trebinje (na lokalitetu Žudojevići) i Gacko-Foča (u Sastavcima), te na ulazu u Neum.\n\nNa dionici magistralne ceste Jablanica-Blidinje, putnička vozila do 3,5t saobraćaju otežano. Za vozila preko 3,5 t saobraćaj je i dalje obustavljen.\n\nNa graničnim prelazima nema dužih zadržavanja za putnička vozila.\n\nZbog registracije putnika po novom sistemu izlaska i ulaska u zemlje Evropske unije (EES, Entry/Exit System), moguća su duža zadržavanja na graničnim prelazima.\n\nGranični prelaz Brčko otvoren je za putnička vozila do 3,5 tone. Zabranjen je saobraćaj za vozila preko pet tona najveće dozvoljene mase na graničnom prelazu Karakaj (kod Zvornika). Teretna vozila preko pet tona preusmjeravaju se na granične prelaze Bratunac ili Rača, dok autobusi mogu koristiti GP Šepak.\n\nTeretna vozila mogu saobraćati na GP Šepak od 09 do 13 sati i od 22 do 06 sati (vikendom mogu prelaziti u terminu od 22 do 06 sati).', '2025-12-03 08:40:14', 'Stanje na putevima', 'https://tuzlanski.ba/wp-content/uploads/2025/11/magla-cesta-1762413842.jpg?v1764747227'),
(9, 'Sud potvrdio nepravilnosti: Univerzitetu \"Kallos\" izrečena trajna zabrana rada', 'Ministarstvo obrazovanja i nauke Tuzlanskog kantona donijelo je nepravosnažno rješenje o trajnoj zabrani rada visokoškolskoj ustanovi Evropski univerzitet \"Kallos\" u Tuzli.\n\nInspekcijskom kontrolom nadležne komisije utvrđene su nepravilnosti koje su konstatovane i u ranijim kontrolama rada ove visokoškolske ustanove.', '2025-12-03 08:41:22', 'Nepravosnažno rješenje', 'https://tuzlanski.ba/wp-content/uploads/2024/11/kallos-1731780799.jpg?v1764698730'),
(10, 'Nagrada za dobre igre: Esmiru Bajraktareviću porasla cijena na Transfermarktu', 'Jedan od najvrijednijih eksponata u izlogu fudbalske reprezentacije Bosne i Hercegovine je PSV-ov Esmir Bajraktarević.\n\nPrije nekoliko dana je prvi put u sezoni odigrao svih 90 minuta i asistirao je u pobjedi svog tima protiv Volendama (3:0).\n\nDanas dolaze nove dobre vijesti kada je riječ o ovom momku. Transfermarkt je ažurirao cijene i Bajraktarevićeva cijena skočila je za dva miliona eura.\n\nDo sada je vrijedio tri, a sada vrijedi pet miliona eura.', '2025-12-03 08:41:56', 'TALENTOVANI ZMAJ ', 'https://tuzlanski.ba/wp-content/uploads/2025/03/esmir-bajraktarevic-2-1742581628.jpg?v1764706572'),
(11, 'Dodik: Naser Orić je obični zlikovac koji nastavlja da laže, bolje bi bilo da objasni neka ubistva', 'Nakon što je ratni komandant Armije RBiH Naser Orić objavio fotografiju na kojoj se nalazi u društvu srbijanskog pjevača Ace Lukasa nastao je verbalni rat da društvenim mrežama.\n\nNajprije se oglasio predsjednik SNSD-a Milorad Dodik koji je kazao da Lukas više neće dobiti dozvolu za pjevanje na području entiteta Republika Srpska. Nakon toga je Lukasu otkazan i koncert na Jahorini. \n\nNaser Orić je kazao da je sve to predimenzionirano, licemjerno i da nema nikakve potrebe da se u toj mjeri satanizuje pjevač Aca Lukas.\n\n[related]1003101[/related] \n\n\"Vidim da se i Dodik oglasio i traži da se Aci zabrani koncert. A zna Dodik da sam i njemu valjao i zvao je kada sam mu trebao. Zna on dobro o čemu ja pričam\", rekao je Orić. \n\nNakon toga se ponovo oglasio Dodik, kazavši da Orić ponovo laže.\n\n\"Naser Orić je obični zlikovac koji nastavlja da laže i izmišlja da je navodno neko od moje rodbine bio sa njim, a prethodno je tvrdio da se čuo i vidio sa mnom. I opet laže, i u prvom i u drugom slučaju. Bolje bi bilo da objasni kako je ubijen sudija Slobodan Ilić i kako je monstruozno masakriran dječak Slobodan Stojanović\", napisao je Dodik.', '2025-12-03 08:42:30', 'NAKON OBJAVLJENE FOTOGRAFIJE', 'https://tuzlanski.ba/wp-content/uploads/2025/12/naser-i-dodik-1764614451.jpg?v1764699900'),
(12, 'Soreca pozvao političare BiH da ne propuste historijsku šansu: Samo nekoliko koraka je ostalo za BiH ', 'Bosna i Hercegovina i dalje ima šansu za napredak na evropskom putu, ali sat otkucava, a politički lideri ne pokazuju odlučnost koja se od njih očekuje.\n\nU poruci objavljenoj nakon neuspjelog sastanka Vijeća ministara BiH, Specijalni predstavnik Evropske unije Luigi Soreca pozvao je domaće vlasti da konačno preuzmu odgovornost i ispune preostale tehničke i političke uslove.\n\nPrema njegovim riječima, članstvo u EU ostaje najbolja garancija stabilnosti i prosperiteta za BiH, ali se taj cilj može dostići tek kada se ispune konkretne obaveze.\n\nMeđu prioritetima su, kako je naveo, usvajanje Zakona o Visokom sudskom i tužilačkom vijeću (VSTV) te Zakona o sudovima, koji moraju biti u skladu s evropskim pravnim normama.\n\nDrugi ključni korak je formiranje tima za pregovore s Evropskom unijom i imenovanje glavnog pregovarača – figure koja će predstavljati državu jednim glasom.\n\nNažalost, dodao je Soreca, Vijeće ministara BiH nije iskoristilo priliku da danas napravi pomak u tom pravcu.\n\nSoreca je podsjetio da istraživanja javnog mnijenja pokazuju jasnu opredijeljenost građana ka evropskoj budućnosti.\n\n\"Većina građana širom zemlje želi BiH u Evropskoj uniji\", naglašava, podsjećajući da je i sama Unija jasno stavila do znanja da BiH ima svoje mjesto u evropskoj porodici.\n\nMeđutim, kako ističe, entuzijazam građana nije dovoljan – političari su ti koji moraju preći s riječi na djela.\n\n\"Ono što nedostaje jeste politička volja\", poručio je Soreca, pozivajući političke aktere da se uozbilje i fokusiraju na ispunjenje preostalih uslova. Kako kaže, \"prozor prilike\" je otvoren, ali neće to ostati zauvijek.', '2025-12-03 08:44:58', 'Put ka EU', 'https://tuzlanski.ba/wp-content/uploads/2025/09/luigi-soreca-1759252240.jpg?v1764697702'),
(13, 'Odluka Vlade TK: Zaposlenima u institucijama slijedi naknada od 300 KM za vjerske praznike ', 'Vlada Tuzlanskog kantona danas je održala 40. redovnu sjednicu.\n\nNa sjednici je Vlada utvrdila da će visina naknade povodom vjerskih praznika za 2025. godinu zaposlenim kod korisnika budžetskih sredstava iznositi 300 KM.\n\nPravo na ovu naknadu imaju svi imaju zaposlenici koji se na dan donošenja ove Odluke nalaze u radnom odnosu kod korisnika budžetskih sredstava i pravosudnih institucija Tuzlanskog kantona.', '2025-12-03 08:45:40', 'SJEDNICA VLADE TK ', 'https://tuzlanski.ba/wp-content/uploads/2025/06/km-konvertibilne-marke-novac-1750837874.jpeg?v1764687887'),
(14, 'Inicijativa Čavalića i Aliefendića: Od Vlade FBiH tražimo povećanje penzija za najmanje 20 posto', 'Zastupnici Admir Čavalić iz Stranke za Bosnu i Hercegovinu i nezavisni zastupnik Almedin Aliefendić podnijeli su Predstavničkom domu Parlamenta FBiH prijedlog izmjena i dopuna Zakona o PIO, čime su pokrenuli novu parlamentarnu proceduru.\n\nU zajedničkom saopćenju za javnost istakli su da od Vlade Federacije BiH očekuju da u Budžetu za 2026. godinu planira sredstva za povećanje penzija od najmanje 20%, jer je to minimum \"pravednosti prema generacijama koje su radile i gradile našu domovinu\".\n\n\"Uvažavajući činjenicu da Vlada Federacije Bosne i Hercegovine tokom 2025. godine nije dostavila u parlamentarnu proceduru najavljeni prijedlog izmjena i dopuna Zakona o penzijskom i invalidskom osiguranju, te uzimajući u obzir složenu socio-ekonomsku situaciju penzionera u Federaciji Bosne i Hercegovine, pristupili smo izradi ovog prijedloga zakona s ciljem unapređenja ekonomsko-socijalnog položaja penzionerske populacije počev od 1. januara 2026. godine. Napominjemo da su predstavnici Vlade ranije najavljivali određene promjene, međutim kako ide kraj godine, sve manje se o tome priča\", naveli su.', '2025-12-03 08:46:16', 'Izmjene zakona o PIO', 'https://tuzlanski.ba/wp-content/uploads/2025/03/penzija-bih23-1741163987.jpg?v1764660263'),
(15, 'Damir Džumhur na romantičnom putovanju zaprosio izabranicu Aidu', 'Naš najbolji teniser Damir Džumhur zaprosio je svoju izabranicu Aidu Čičkušić na romantičnom putovanju u Finskoj. \n\nOvu sretnu vijest podijelila je njegova izabranica na svom Instagram profilu. \n\n\"Nakon što sam napokon smirila utiske, mogu da podijelim sa vama jednu preslatku vijest. Rekla sam DA\", napisala je Čičkušić uz objavljenu fotografiju. ', '2025-12-03 08:48:04', 'Podijelili sretnu vijest', 'https://tuzlanski.ba/wp-content/uploads/2025/12/dzumhur-zaruke-1764702885.jpg?v1764702895'),
(16, 'Haris Tabaković nezaustavljiv, večeras zabio majstorski gol ', 'Haris Tabaković postigao je deveti gol u sezoni za Borussiju M\'Gladbach.\n\nNjegov tim je poražen 2:1 od St. Paulija u duelui osmine finala Kupa Njemačke, a Haris je u 56. minuti majstorski pogodio glavom.\n\nTrijumf i prolaz St. Pauliju u četvrtfinale osigurao je Oppie u 83. minuti.\n\nTabaković igra redovno u prvih 11 Borussije, a sa devet golova je prvi strijelac svoje ekipe. Sedam je zabio u ligi, a dva u Kupu. Ukupno je odigrao 14 utakmica.', '2025-12-03 08:48:41', 'Deveti u sezoni', 'https://tuzlanski.ba/wp-content/uploads/2025/12/tabakovic-gol-1764700683.jpg?v1764700816'),
(17, 'Zaboravljeni Hamulić eksplodirao na Kup utakmici: Tri gola i asistencija za ubjedljivu pobjedu', 'Junak u pobjedi Volosa bio je bh. internacionalac Said Hamulić, koji je postigao hat-trick.\n\nDomaćini su u prvom poluvremenu vodili 2:0 već nakon 13 odigranih minuta, a pogađali su Assehnoun i Santis.\n\nU drugom smo gledali pravu rapsodiju Volosa, koji je preko razigranog Hamulića do vrha napunio mrežu Egaleoa.\n\nPrvo je u 57. minuti zabio za 3:0, da bi drugi gol postigao pet minuta kasnije.\n\nIgrala se 83. minuta kada je Hamulić postigao hat-trick, a u 83. minuti konačanih 6:0 postavio je Assehnoun.\n\nTreba dodati da je u Volosu Hamulić dosad postigao ukupno pet golova što je odlična najava uzmemo li u obzir višemjesečni golgeterski post.', '2025-12-03 08:49:11', 'POVRATAK GOLGETERSKE FORME', 'https://tuzlanski.ba/wp-content/uploads/2025/12/said-hamulic-pogodak2-1764707153.jpg?v1764707162'),
(18, 'Sutra u Tuzli počinju međunarodni književni susreti \"Cum grano salis\"', 'Tuzla će ponovo postati epicentar književnosti regije. Od 3. do 6. decembra 2025. godine, u ovom gradu bit će održani 24. međunarodni književni susreti Cum grano salis, koji već više od dvije decenije okupljaju autore, kritičare, zaljubljenike u pisanu riječ i poštovaoce lika i djela Meše Selimovića.\n\nTradicija duga više od dvije decenije\n\nKnjiževni susreti \"Cum grano salis\" osnovani su 2001. godine, a centralni događaj festivala je dodjela prestižne Nagrade \"Meša Selimović\" za najbolji roman objavljen na prostoru Bosne i Hercegovine, Hrvatske, Srbije i Crne Gore. Ovogodišnja nagrada dodijelit će se za najbolji roman iz 2024. godine, a svečana ceremonija bit će upriličena u subotu, 6. decembra, u 19:00 sati u Ateljeu Ismet Mujezinović.\n\nRaznolik i bogat program\n\nProgram susreta nudi bogat sadržaj – od izložbi, scenskih izvedbi, književnih predstavljanja do panela i diskusija sa autorima i stručnjacima iz regije.\n\nVeć prvog dana, 3. decembra, planirana je izložba povodom 100 godina od rođenja Derviša Sušića, te predstava \"Posljednja ljubav Hasana Kaimije\" u Narodnom pozorištu Tuzla.\n\nDan kasnije, 4. decembra, biće predstavljeni najbolji literarni radovi učenika iz Gimnazije \"Meša Selimović\", kao i književna večer posvećena djelu Nijaza Alispahića u Međunarodnoj galeriji portreta.\n\nPetak, 5. decembra, rezervisan je za predstavljanje romana koji su ušli u uži izbor za nagradu \"Meša Selimović\":\n\n- Knjiga o Almi – Adisa Bašić\n- Pesak piskar – Milenko Bodirogić\n- Derviš i Zulejha – Đorđe Matić\n- Četiri jame i bedž – Nada Gašić\n- Žigice – Jurica Pavičić\n\nU nastavku večeri, publici će biti predstavljen roman Zima zaručnika autora Enesa Karića i Osmana Halilovića, uz umjetnički program u kojem učestvuju Ermin i Sadika Avdić.\n\nZavršnica uz priznanje i sjećanje\n\nPosljednji dan susreta, 6. decembra, počinje u 12:00 sati omažom Filipu Davidu pod nazivom „Tako je govorio Filip David“. U večernjim satima uslijedit će svečana dodjela nagrade \"Meša Selimović\", čime će i zvanično biti zatvoreni ovogodišnji susreti.\n\nUlaz je na sve programe slobodan', '2025-12-03 08:50:12', 'OD 3. DO 6. DECEMBRA', 'https://tuzlanski.ba/wp-content/uploads/2016/08/cum-grano-salis.jpg?v1764689067'),
(19, 'Svečani koncert u BKC-u: Tuzla obilježava dan kada je sevdalinka uvrštena na UNESCO listu', 'Bosanski kulturni centar Tuzlanskog kantona 4. decembra 2025. godine bit će domaćin svečanog koncerta posvećenog obilježavanju dana kada je sevdalinka uvrštena na UNESCO listu nematerijalne kulturne baštine čovječanstva.\n\nKoncert pod nazivom \"U srcu Bosne, u srcu svijeta\" počinje u 19 sati, a organizuje ga Udruženje Sevdalija Tuzla.\n\nPublika će imati priliku uživati u bogatom programu koji okuplja veliki broj izvođača, među kojima su vokalni solisti Udruženja Sevdalija Tuzla, Esad Kovačević, Džavid Pamuković, Hajrudin Udvinčić – Hazre, Mehmedalija Dropić – Dale i Fahrudin Bajrić.\n\nNastupit će i Vokalni ansambl JU BKC TK Tuzla te izvorna grupa zurle i bubnjevi.\n\nSve izvođače pratit će orkestar Udruženja Sevdalija Tuzla, pod vodstvom Abaza Bijedića.\n\nOrganizatori pozivaju građane da prisustvuju ovom posebnom muzičkom događaju i zajedno obilježe važan dan za bosanskohercegovačku muzičku tradiciju.', '2025-12-03 08:50:41', '4. Decembra', 'https://tuzlanski.ba/wp-content/uploads/2025/12/sendalinka-ilustracija4-1764674412.jpg?v1764674418'),
(20, 'Netflix tiho ukinuo popularnu funkciju: Da li ste je koristili?', 'Netflix je počeo da gasi popularnu funkciju koja omogućava slanje slike sa mobilnog telefona na televizor.\n\nKonkretno, ukida se mogućnost da film ili seriju puštenu na Android telefonu prebacite na TV preko Google Cast-a.\n\nNetflix je ovu promjenu tiho potvrdio i na svojim stranicama.\n\n\"Netflix više ne podržava prenos sadržaja sa mobilnih uređaja na većinu televizora i TV striming uređaja. Za upravljanje Netflix-om moraćete da koristite daljinski upravljač koji ste dobili uz televizor ili striming uređaj\", navodi kompanija.\n\nDrugim riječima, ako ste započeli gledanje serije ili filma na telefonu, a zatim željeli da pomoću Cast dugmeta prebacite reprodukciju na televizor - to više nije moguće.\n\nGašenje funkcije je počelo sredinom novembra, a većina korisnika tek sada osjeća posljedice.\n\nPodsjetimo, Netflix je AirPlay podršku ukinuo još 2019. godine.\n\nPrema informacijama na zvaničnoj stranici Netflix podrške, Cast je i dalje dostupan na starijim Chromecast uređajima i televizorima koji imaju ugrađen Google Cast, ali samo korisnicima skupljih paketa bez reklama.\n\nU BiH su svakako dostupni samo paketi bez reklama, pa dio korisnika i dalje može da šalje sliku sa telefona na TV.', '2025-12-03 08:52:15', 'Google Cast', 'https://tuzlanski.ba/wp-content/uploads/2022/07/netflix.jpg?v1764623149'),
(21, 'Ovaj predmet u kući širi alergene i prljavštinu, a ne pere se tako često ', 'Stručnjaci su otkrili da prosječan stanovnik nije oprao svoj tepih ili stazu još od juna. Potrebno ih je temeljito očistiti, jer to može spriječiti širenje bakterija.\n\nTepihe i staze trebalo bi prati jednom mjesečno, ali čak 40% ljudi to ne radi. U prosjeku, te se stvari peru svakih pet mjeseci.\n\nKako dolazi zima, mnogi će uključiti grijanje, što može uzrokovati kruženje alergena po kući. Stručnjaci upozoravaju da mrtve ćelije i izmet grinje mogu ostati zarobljeni u tkaninama sve dok se ne operu – a mogu se proširiti po cijelom domu kada se uključi grijanje. Svaka deseta osoba pere svoje tepihe i prostirke samo jednom godišnje ili čak rjeđe, piše Express.\n\nZato stručnjaci savjetuju domaćinstvima da operu tepihe prije nego što uključe grijanje, kako bi spriječili širenje alergena i prljavštine po kući.\n\n\"Naše istraživanje pokazuje da su prostirke i tepisi među najzanemarenijim predmetima u kući kada je riječ o čišćenju. Koriste se svakodnevno, više puta dnevno, često u prometnim dijelovima doma poput ulaza, hodnika i dnevnih soba. Dizajnirani su da upijaju prljavštinu i prašinu – ali ljudi im ne posvećuju istu pažnju kao posteljini ili jastučnicama\", kazala je Michelle Byrne, menadžerica marketinga proizvoda.\n\nDodala je da bi pranje tepiha jednom mjesečno trebalo postati kućna navika, a mašinsko pranje je najefikasniji način za uklanjanje prljavštine i bakterija, uz uštedu vremena.\n\nStručni savjeti za čišćenje tepiha\n\n1. Otresite prljavštinu\n\nPrvi korak je da tepih iznesete napolje i dobro ga protresete ili istresete da bi se oslobodio nakupljene prašine. Ovo može ukloniti čestice koje usisivač ne pokupi i pomoći u eliminaciji alergena.\n\n2. Usisavajte svake sedmice\n\nPokušajte usisavati tepih barem jednom sedmično – češće ako se nalazi u prometnim prostorijama poput hodnika ili dnevne sobe.\n\n3. Perite mjesečno\n\nPerive tepihe stavite u mašinu barem jednom mjesečno na 40°C ili više, kako biste uklonili bakterije i duboku prljavštinu.\n\n4. Uklanjajte mrlje odmah\n\nKada se mrlja pojavi, reagujte odmah. Uklonite je tapkanjem čistom krpom i blagim deterdžentom. Nemojte trljati, jer to može gurnuti mrlju dublje u tkaninu.\n\n5. Dobro osušite da spriječite plijesan\n\nUvijek pustite da se tepisi potpuno osuše nakon pranja kako biste spriječili razvoj plijesni i neugodnih mirisa. Sušenje na zraku je najbolje, ali ako je dozvoljeno prema etiketi, možete ih i osušiti u mašini na niskoj temperaturi.', '2025-12-03 08:53:00', 'Izvor bakterija', 'https://tuzlanski.ba/wp-content/uploads/2025/12/ciscenje-kuca-1764691351.jpg?v1764691375'),
(22, 'Jeste li ikada pravili kiflice bez kvasca? Isprobajte recept u kojemu je samo jedan sastojak ključan', 'Zamislite jutro kada želite tople, mekane i mirisne kiflice, ali nemate vremena da čekate da tijesto naraste. Ne brinite – rješenje postoji, i to je brže nego što mislite.\n\nKiflice bez kvasca su savršeno pecivo za doručak: mekane, hrskave i tako sočne da se tope u ustima. A trik sa jogurtom osigurava da ostanu svježe i sutradan, kao da ste ih tek izvadili iz rerne.\n\nZašto su ove kiflice posebne?\n\nTajna nije samo u brzini pripreme, već u domaćinskom triku koji daje testu vazdušastu strukturu i vlažnost – jogurt reaguje sa praškom za pecivo i daje kiflicama savršenu teksturu.\n\nSastojci:\n\n- 500 g mekog brašna (i malo za posipanje)\n- 200 g čvrstog jogurta\n- 100 ml ulja\n- 1 prašak za pecivo\n- 1 jaje\n- 1 kašičica soli\n- Fil po želji.\n\nPriprema:\n\nU većoj posudi pomiješajte brašno, prašak za pecivo i so. Dodajte jogurt i ulje, a jaje ostavite za premazivanje. Zamijesite glatko, mekano tijesto. Nema čekanja – pošto nema kvasca, tijesto odmah možete koristiti.\n\nPodijelite tijesto na dva jednaka dijela i razvaljajte svaki u krug. Krug podijelite na 8 trouglova. Na širi dio svakog stavite fil po želji i zarolajte kiflicu.\n\nPoredajte kiflice na pleh obložen papirom za pečenje. Premažite umućenim jajetom i po želji pospite susamom. Pecite u rerni zagrijanoj na 200°C oko 15–20 minuta, dok ne dobiju zlatnu boju.\n\nAko želite da kiflice dobiju izgled kao iz stare pekare, prije pečenja premažite ih žumancetom pomiješanim sa kašikom mlijeka. To im daje savršenu zlatnu boju i dodatni sjaj.\n\nZašto ostaju mekane i sutradan?\n\nJogurt je ključ – on čuva vlažnost tijesta, a zajedno sa praškom za pecivo daje kiflicama divnu vazdušastu strukturu. Rezultat? Mekano, mirisno pecivo koje traje i sutradan.\n\nOve kiflice su jednostavne, brze i idealne za svako jutro. Nema više kupovnih peciva – sada znate tajnu domaće, savršene užine.', '2025-12-03 08:53:29', 'Oduševit će vas', 'https://tuzlanski.ba/wp-content/uploads/2025/12/kiflice-1764609199.jpg?v1764609416'),
(23, 'Zimi rijetko otvarate prozore? Ovo su razlozi zbog kojih time možete ugroziti zdravlje ukućana', 'Nedostatak svježeg zraka pretvara vaš dom u leglo bakterija, vlage i toksina, a pravilno provjetravanje ključno je za očuvanje imuniteta, piše Ordinacija.\n\nMnogima je pomisao na otvaranje prozora dok su vanjske temperature blizu nule potpuno strana, prvenstveno zbog straha od gubitka dragocjene topline i povećanja računa za grijanje. \n\nMeđutim, ova uobičajena zabluda dovodi do toga da zrak u našim domovima tokom zime postaje znatno lošije kvalitete, a prema nekim istraživanjima, unutrašnji zrak može biti čak pet puta zagađeniji od vanjskog.\n\nKada zatvorimo prozore i vrata kako bismo sačuvali toplinu, zapravo zarobljavamo onečišćivače, alergene i ustajali zrak unutar četiri zida, stvarajući idealne uvjete za razvoj zdravstvenih problema.\n\nSituaciju dodatno pogoršavaju moderni građevinski trendovi i ugradnja visokokvalitetne PVC stolarije koja, iako energetski učinkovita, hermetički zatvara prostor i onemogućuje prirodnu izmjenu zraka.\n\nBez redovitog dotoka kisika, prostorije postaju zagušljive, a koncentracija štetnih tvari drastično raste, što vaš dom pretvara u toksično okruženje upravo u periodu kada nam je imunitet najpotrebniji za borbu protiv sezonskih virusa.\n\nNajveći neprijatelj – vlaga\n\nJedan od najvećih neprijatelja zdravog doma zimi je prekomjerna vlaga koja nastaje svakodnevnim životnim aktivnostima. Prosječno četveročlano kućanstvo disanjem, znojenjem, kuhanjem, tuširanjem i sušenjem odjeće dnevno u zrak ispusti između 6 i 12 litara vode.\n\nAko taj vlažni zrak ne zamijenimo suhim vanjskim zrakom, on se kondenzira na hladnijim površinama poput prozora i vanjskih zidova, stvarajući savršenu podlogu za razvoj plijesni i gljivica.\n\nOsim što narušavaju estetiku prostora, spore plijesni su iznimno opasne za disajni sistem i mogu izazvati niz tegoba, od alergijskih reakcija i astme do hroničnog umora i glavobolja.\n\nZato je kontrola vlažnosti ključna, a idealan nivo vlage u zatvorenom prostoru trebao bi se kretati između 35% i 60%, ovisno o vanjskoj temperaturi, kako bi se spriječilo isušivanje sluznice, ali i pojava grinja i bakterija koje bujaju u prevlažnim uvjetima.\n\nZdravstvene posljedice boravka u neprovjetrenim prostorijama mnogo su ozbiljnije nego što većina ljudi pretpostavlja. \n\nU zatvorenom prostoru cirkulira oko 900 različitih čestica i biološkog materijala, uključujući viruse, bakterije, perut kućnih ljubimaca i hlapljive organske spojeve (VOC) koji isparavaju iz namještaja, sredstava za čišćenje, pa čak i osvježivača zraka. \n\nNedostatak ventilacije dovodi do nakupljanja ugljičnog dioksida, što uzrokuje pad koncentracije, pospanost, iritabilnost i onaj dobro poznati osjećaj \"teške glave\".', '2025-12-03 08:54:13', 'VLAGA, BAKTERIJE, TOKSINI', 'https://tuzlanski.ba/wp-content/uploads/2025/12/prozor-1764667225.jpg?v1764667512'),
(24, 'Zeleni znakovi ograničenja: Da li znate gdje se koriste i koja je njihova svrha?', 'Znakovi ograničenja brzine obično imaju crveni obrub, ali jeste li znali da postoje i oni sa zelenim rubom?\n\nTakvi znakovi već se koriste na cestama u Velikoj Britaniji, a sada i Francuska i Španija razmatraju pilot-programe u kojima bi se postavili na odabrane dionice saobraćajnica.\n\nDok crveno-bijeli znakovi označavaju obavezna ograničenja brzine, zeleno-bijeli predstavljaju preporuku, piše HAK Revija.\n\nCilj ovih znakova je sugerisati odgovarajuću brzinu na cesti gdje su postavljeni, a vožnja iznad te brzine ne podrazumijeva automatski kaznu.\n\nU nekim zakonima se čak koristi termin \"savjetodavno ograničenje brzine\", što jasno pokazuje da se radi o preporučenoj, a ne obaveznoj brzini.', '2025-12-03 08:54:44', 'Odabrane dionice', 'https://tuzlanski.ba/wp-content/uploads/2025/11/znakovi-1764515590.jpg?v1764516195'),
(25, 'Novi Cupra Leon VZ stiže sa 325 KS i postavkama kojima izaziva Volkswagen Golf GTI', 'Cupra je predstavila najsnažniji Leon s prednjim pogonom ikada, sa 325 KS i performansama koje izazivaju Volkswagen Golf GTI.\n\nŠpanci ponovo pomiču granice performansi, jer Cupra je evidentno jedan od vodećih brendova na tržištu sportskih i ekskluzivnih automobila. Njihova najnovija ponuda nije ništa drugo nego najsnažniji Cupra Leon s prednjim pogonom ikada, piše BIHAMK.\n\nInspirisan takmičarskim automobilom CUPRA León VZ TCR Racing, novi Leon VZ dostiže vrhunske nivoe performansi sa ograničenom serijom koja će oduševiti vozače koji vole sportski duh i performanse. Model sa poboljšanom dinamikom izaziva Volkswagen Golf GTI Edition 50, koji nudi isti tehnički paket.\n\nBrend je prenio preciznost i iskustvo stečeno u svijetu motosporta na cestovni automobil koji nudi odličnu ravnotežu između čistog sportskog automobila i udobnosti cestovnog vozila. Izrađena na platformi MQB Evo, šasija je fino podešena. I opruge i amortizeri su kalibrisani za njene specifične potrebe.\n\nVozač može prilagoditi profil šasije svom ukusu, dok sportski upravljač nudi brz i vrlo precizan odziv. Da bi održao kontrolu nad ovom zvijeri na točkovima, brend koristi Akebono kočnice sa šestoklipnim čeljustima i ventiliranim i perforiranim prednjim diskovima. Svemu tome dodaje se sportski izduvni sistem sa četiri bakreno obrađena otvora.\n\nU enterijeru vlada sportska atmosfera. Tamni hromirani završni slojevi, uključujući i satelitske komande, dodaju sofisticirani dodir koji upotpunjuje bogatu standardnu ​​tehnologiju.\n\nŠto se tiče mehaničkih aspekata novog Leona VZ, pogled ispod haube otkriva 2,0-litarski TSI četverocilindarski benzinski motor. Ovaj poznati turbobenzinac razvija 325 KS i 420 Nm maksimalnog obrtnog momenta. Uparen je sa sedmostepenim DSG automatskim mjenjačem s dvostrukim kvačilom i ima konfiguraciju pogona na prednje točkove.\n\nOgraničen na 1.500 jedinica, bit će lansiran u prvom kvartalu 2026. godine, dajući CUPRA Tribeu priliku da osjeti snagu i preciznost trkačkog duha brenda - prije dolaska VZ TCR-a.', '2025-12-03 08:55:15', 'Jedan od vodećih brendova', 'https://tuzlanski.ba/wp-content/uploads/2025/11/cupra-1764440719.jpg?v1764440897'),
(26, 'U BiH uvezeno 80.033 automobila: Listu 10 najskupljih predvodi Porsche vrijedan 511.118 KM', 'Ove godine je u Bosnu i Hercegovinu, do oktobra, uvezeno 80.033 automobila od čega je 71.909 polovnih i 8.124 nova.\n\nPrema podacima, vrijednost uvezenih automobila je veća od 1,19 milijardi KM.\n\nZanimljivo, u ovih 80.033 vozila, samo su 194 električna automobila vrijedna oko 10 miliona KM.\n\nNajskuplji uvezeni automobil do oktobra 2025. godine je Porsche 911 GT3 RS vrijedan 511.118 KM.\n\nPorsche 911 GT3 RS – 401.041 KM.\n\nMercedes-BENZ G-klasa AMG G63 – 392.699 KM\n\nPorsche-911 Turbo – 381.638 KM\n\nPorsche-911 GT3 RS – 379.165 KM\n\nMercedes AMG SL63 – 367.761 KM\n\nPorsche-911 GT3 RS – 355.042 KM\n\nMercedes AMG G63 – 354.935 KM\n\nPorsche-911 GT3 – 349.410 KM\n\nPorsche-911 GT3 – 325.425 KM', '2025-12-03 08:55:51', 'STATISTIKA DO OKTOBRA 2025.', 'https://tuzlanski.ba/wp-content/uploads/2025/11/porsche-ilustracija5-1764358654.jpg?v1764358696');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `ime` varchar(50) NOT NULL,
  `prezime` varchar(50) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(100) NOT NULL,
  `role` enum('admin','user') NOT NULL DEFAULT 'user'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `ime`, `prezime`, `username`, `password`, `email`, `role`) VALUES
(1, 'Medina', 'Mustacevic', 'admin', 'asdf', 'admin@example.com', 'admin'),
(3, 'Mirza', 'Mustačević', 'mirzam', 'asdf', 'mirza@mustacevic.com', 'user');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `news`
--
ALTER TABLE `news`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `news`
--
ALTER TABLE `news`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=27;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
